language: java
jdk:
  - openjdk8
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn test -Dspring.profiles.active=test org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=hairless_plink
cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/flink-1.11.1"
before_install:
  - export FLINK_HOME=$HOME/flink-1.12.1
  - if [ ! -d $FLINK_HOME/bin ]; then curl https://mirrors.bfsu.edu.cn/apache/flink/flink-1.12.1/flink-1.12.1-bin-scala_2.11.tgz
    | tar zxf - -C $HOME; fi
env:
  global:
    secure: tmn1eLtzAdQ50gwN8kkTCbO3hXPiz7rkI9txDvtoMK5mbSlYfaXBOaTEdB6N/2WqFDwiyr2PjTzWaUjapWvnSFXnGA54+jEGhSihhctKjcxz+d5pSlzjbbnG7gTqO7RXP8UJAdhIF5n2nhkLori7jFDw/c03js55ueEVrgna72rXDZMUvdYdoBp89itybVs9i4wRbVM/Cf2BVBT/41KOPJANl78Hu8FsSq0A/40/uWHTOm9dbdBv9gqeAGkofnvocrg9HDucA7VUZe5TorHtJcUn0Xh9qdjn4U5j0AEGEy4Aj5uC97kPbxbI8NPfueZjAqF4kx2qjakdJpDx+/aCx9iaIjJAenY4SZQH4i2kCvgJclrFLYVmDVaXWh1B92B1Uee5ZtH4LBttiaUkNfoUvB6wkO0TfyNYi5NHwp9H2cDnDyvmEoNeH7gZKW5/hMHdCwL2V+hCg64E3dWt+q8Fxwb+c7Km0OqNrUz0xBCEuLl2llyWOvMclP3Oz+la0GOBAL2G04jbC4f/BllF9w6Uful93UAPqavk/kEBr/FK2c/N/g7nBpv/uHnsZFhiRKPSsiPb1+7JWVzIXCY/ZYvkMIpIEfQT4bmpzbfCzyoQCPW2nM+biOkU+zGqf4wgBsw59ZpC1kjafqB1tZmu7Jf1RBQVIGfBs/tRfg3Fq77yJLY=
addons:
  sonarcloud:
    organization: "hairless"
    token:
      secure: "tmn1eLtzAdQ50gwN8kkTCbO3hXPiz7rkI9txDvtoMK5mbSlYfaXBOaTEdB6N/2WqFDwiyr2PjTzWaUjapWvnSFXnGA54+jEGhSihhctKjcxz+d5pSlzjbbnG7gTqO7RXP8UJAdhIF5n2nhkLori7jFDw/c03js55ueEVrgna72rXDZMUvdYdoBp89itybVs9i4wRbVM/Cf2BVBT/41KOPJANl78Hu8FsSq0A/40/uWHTOm9dbdBv9gqeAGkofnvocrg9HDucA7VUZe5TorHtJcUn0Xh9qdjn4U5j0AEGEy4Aj5uC97kPbxbI8NPfueZjAqF4kx2qjakdJpDx+/aCx9iaIjJAenY4SZQH4i2kCvgJclrFLYVmDVaXWh1B92B1Uee5ZtH4LBttiaUkNfoUvB6wkO0TfyNYi5NHwp9H2cDnDyvmEoNeH7gZKW5/hMHdCwL2V+hCg64E3dWt+q8Fxwb+c7Km0OqNrUz0xBCEuLl2llyWOvMclP3Oz+la0GOBAL2G04jbC4f/BllF9w6Uful93UAPqavk/kEBr/FK2c/N/g7nBpv/uHnsZFhiRKPSsiPb1+7JWVzIXCY/ZYvkMIpIEfQT4bmpzbfCzyoQCPW2nM+biOkU+zGqf4wgBsw59ZpC1kjafqB1tZmu7Jf1RBQVIGfBs/tRfg3Fq77yJLY=" # encrypted value of your token
